parameters:
#    blogger_mistakes.example.class: Mistakes\MistakesTestBundle\Example

services:
#    blogger_mistakes.example:
#        class: %blogger_mistakes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
