parameters:
#    mistakes.example.class: Mistakes\MistakesBundle\Example

services:
#    mistakes.example:
#        class: %mistakes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
